version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.2.1
  pocket: pocket/circleci-orbs@1.2.7

# Workflow shortcuts
not_main: &not_main
  filters:
    branches:
      ignore:
        - main

only_main: &only_main
  filters:
    branches:
      only:
        - main

not_dev: &not_dev
  filters:
    branches:
      ignore:
        - dev

only_dev_main: &only_dev_main
  filters:
    branches:
      only:
        - dev
        - main

not_dev_main: &not_dev_main
  filters:
    branches:
      ignore:
        - dev
        - main

only_dev: &only_dev
  filters:
    branches:
      only:
        - dev

workflows:
  all:
    jobs:
      - pocket/run_codebuild:
          <<: *only_dev
          context: pocket
          aws-access-key-id: Dev_AWS_ACCESS_KEY
          aws-secret-access-key: Dev_AWS_SECRET_ACCESS_KEY
          aws-region: Dev_AWS_DEFAULT_REGION
          name: run_dev_code_build
          codebuild-project-name: PocketEventBridge-Dev
          codebuild-project-branch: dev

      - pocket/run_codebuild:
          <<: *only_main
          context: pocket
          aws-access-key-id: Prod_AWS_ACCESS_KEY
          aws-secret-access-key: Prod_AWS_SECRET_ACCESS_KEY
          aws-region: Prod_AWS_DEFAULT_REGION
          name: run_prod_code_build
          codebuild-project-name: PocketEventBridge-Prod
          codebuild-project-branch: main

      # Notify sentry of main deployment
      - pocket/sentry_release_notification:
         <<: *only_main
         name: sentry-release-notification-prod
         context: pocket
         repository_name: Pocket/${CONSTRUCT_NAME}
         sentry_project_name: ${CONSTRUCT_NAME}
         sentry_env: production
         sentry_org: pocket
         workspace-path: /tmp/workspace
         requires:
           - run_prod_code_build

      # Notify sentry of dev deployment
      - pocket/sentry_release_notification:
         <<: *only_dev
         name: sentry-release-notification-dev
         context: pocket
         repository_name: Pocket/${CONSTRUCT_NAME}
         sentry_project_name: ${CONSTRUCT_NAME}
         sentry_env: development
         sentry_org: pocket
         workspace-path: /tmp/workspace
         requires:
           - run_dev_code_build
